import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700", "800"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Yuv Raj Enterprise",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={inter.className}>
      <body className="scroll-smooth bg-white text-black">
        <Navbar />
        {/* Spacer to prevent layout shift due to fixed navbar */}
        {/* <div className="h-[92px]" aria-hidden="true" /> */}
        {children}
      </body>
    </html>
  );
}
